

version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      -  MONGO_INITDB_ROOT_USERNAME=root
      -  MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db: 